---
- hosts: all
  remote_user: root
  vars_files:
   - playbook_variables.yml
  tasks:
# Update system and installing open-ssh client and CA certificates and software update, may take a few minutes
   - name: Installing open-ssh and CA certificates and yum update, may take a few minutes 
     yum: name=openssh-clients state=present
     yum: name=ca-certificates state=present
     yum: name=postfix state=present
     yum: name=* state=latest        
# Diabling Firewall
   - name: Disabling Firewall service
     service: name=iptables state=stopped
# Creating Illumio User
   - name: Creating group "illumio"
     group: name=illumio state=present
   - name: creating user "illumio"
     user: group=illumio name=illumio password=illumio 
# Creating Use ENV
   - name: Adding ENV File in bash_profile
     lineinfile: dest=/home/illumio/.bash_profile line="export ILLUMIO_RUNTIME_ENV=/opt/illumio_pce_config/runtime_env.yml"
     lineinfile: dest=/home/illumio/.bashrc line="export ILLUMIO_RUNTIME_ENV=/opt/illumio_pce_config/runtime_env.yml"
     lineinfile: dest=/root/.bash_profile line="export ILLUMIO_RUNTIME_ENV=/opt/illumio_pce_config/runtime_env.yml"
     lineinfile: dest=/root/.bashrc line="export ILLUMIO_RUNTIME_ENV=/opt/illumio_pce_config/runtime_env.yml"

# Remove runtime file
   - name: Remove runtime file
     file: path=/opt/illumio_pce_config/runtime_env.yml state=absent
# Adding hostnames to /etc/hosts        
   - name: Adding Core0 in hosts File
     lineinfile: dest=/etc/hosts line="{{core0_ip}}      {{core0_hostname}}"
   - name:  Adding Core1 in hosts file
     lineinfile: dest=/etc/hosts line="{{core1_ip}}      {{core1_hostname}}"
   - name: Adding D0 to hosts file
     lineinfile: dest=/etc/hosts line="{{data0_ip}}      {{data0_hostname}}"
   - name: Adding D1 to hosts file
     lineinfile: dest=/etc/hosts line="{{data1_ip}}      {{data1_hostname}}"
   - name: Adding PCE FQDN to /etc/hosts
     lineinfile: dest=/etc/hosts line="{{pce_ip}}        {{pce_fqdn}}"
   - name: Adding name of Ven Repo
     lineinfile: dest=/etc/hosts line="{{ven_ip}}        {{ven_repo}}"
# Create directories
   - name: Creating /tmp/illumio_ephemeral_data Directory
     file: path=/tmp/illumio_ephemeral_data state=directory owner=illumio group=illumio mode=0755
   - name: Creating ssl directory
     file: path=/opt/illumio_pce/ssl state=directory owner=illumio group=illumio mode=0755
   - name: Creating illumio_pce_config directory
     file: path=/opt/illumio_pce_config state=directory owner=illumio group=illumio mode=0755
   - name: Creating illumio_pce_data/log directory
     file: path=/opt/illumio_pce_data/log state=directory owner=illumio group=illumio mode=0755
   - name: Creating illumio_pce_data/persistent directory
     file: path=/opt/illumio_pce_data/persistent state=directory owner=illumio group=illumio mode=0755
   - name: Creating illumio_pce_data/runtime directory
     file: path=/opt/illumio_pce_data/runtime state=directory owner=illumio group=illumio mode=0755
   - name: Creating Directory 6
     file: path=/opt/illumio_pce_config/ssl state=directory owner=illumio group=illumio mode=0755
   - name: Creating Directory 7
     file: path=/tmp/illumio_ephemeral_data/keys state=directory owner=illumio group=illumio mode=0755
   - name: Creating Directory 7
     file: path=/var/illumio_log_data/log state=directory owner=illumio group=illumio mode=0755
   - name: Creating runtime_env file
     file: path=/opt/illumio_pce_config/runtime_env.yml state=touch owner=illumio group=illumio mode=0755
# Create ENV YAML File
   - name: ADDING ---
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="---"
   - name: Adding path to install_root
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="install_root{{':'}} /opt/illumio_pce"
   - name: Adding runtime root
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="runtime_data_root{{':'}} /opt/illumio_pce_data/runtime"
   - name: Adding a config line
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="persistent_data_root{{':'}} /opt/illumio_pce_data/persistent"
   - name: Adding ephemeral data
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="ephemeral_data_root{{':'}} /tmp/illumio_ephemeral_data"
   - name: adding logfile
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="log_dir{{':'}} /opt/illumio_pce_data/log"
   - name: adding Key Cache File
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="private_key_cache_dir{{':'}} /tmp/illumio_ephemeral_data/keys"
   - name: Adding FQDN to runtime_env
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="pce_fqdn{{':'}} {{pce_fqdn}}"
   - name: Adding Service Discovery FQDN
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="service_discovery_fqdn{{':'}} {{service_discovery_fqdn}}"
   - name: Adding Cluster IP
     lineinfile:  dest=/opt/illumio_pce_config/runtime_env.yml line="cluster_public_ips{{':'}}"
   - name: Adding Cluster FQDN
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="  cluster_fqdn{{':'}}"
   - name: Adding IPs to file
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="    - {{pce_ip}}"
   - name: Adding a key bundle
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="web_service_certificate{{':'}} /opt/illumio_pce/ssl/{{cert}}"
   - name: Add location of key
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="web_service_private_key{{':'}} /opt/illumio_pce/ssl/{{key}}"
   - name: encryption
    # lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="service_discovery_encryption_key{{':'}} 6h09ACGeLksZXkG5OtkcDw=="
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="service_discovery_encryption_key{{':'}} {{service_discovery_encryption_key}}"
   - name: Display Name
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="email_display_name{{':'}} {{email_display_name}}"
   - name: adding Ven repo URL
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="ven_repo_url{{':'}} https://{{ven_repo}}{{':'}}8443/onpremgCBURz8Y4zkGk1u7N9ialjPGlZ"
   - name: adding Ven Repo IP
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="ven_repo_ips{{':'}}"
   - name: adding IP     
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line=" - {{ven_ip}}"
   - name: Adding Email Address
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml  line="email_address{{':'}} {{email_address}}"
   - name: Display Email
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="smtp_relay_address{{':'}} {{smtp_relay_address}}"
   #- name: Internal IP
    # lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="internal_service_ip{{':'}} {{internal_service_ip}}"
  # copying Certificates to systems
   - name: Copying Certificates to System
     copy: src={{cert}} dest=/opt/illumio_pce/ssl/ owner=illumio group=illumio mode=0755
   - name: Copying Certificate to Anchor
     copy: src={{cert}} dest=/etc/pki/ca-trust/source/anchors/
   - name: Copying Certficate Key
     copy: src={{key}} dest=/opt/illumio_pce/ssl/ owner=illumio group=illumio mode=0755
  # Update Anchor on on ssl_certs
   - name: Update anchors in certificate trust
     command: "update-ca-trust enabble"
     command: "update-ca-trust extract"

 # Copying MNC software onto
   - name: copying MNC software on Nodes
     unarchive: src={{software}} dest=/opt/illumio_pce
   - name: changing ownership of illumio_pce
     command: "chown -R illumio:illumio /opt/illumio_pce"

# Core 0 Specific tasks
- hosts: core0
  remote_user: root
  vars_files:
    - playbook_variables.yml
  tasks:
   - name: Adding role into config Core0
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="node_type{{':'}} core0"
   - name: Changing hostname file  on Core0
     lineinfile: dest=/etc/sysconfig/network line="HOSTNAME={{core0_hostname}}"
   - name: Changing hostname
     hostname: name={{core0_hostname}}
   - name: Restart service on Core0
     command: "service network restart"
# core1 specific config
- hosts: core1
  remote_user: root
  vars_files:
    - playbook_variables.yml
  tasks:
   - name: Adding a role to core 1
     lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="node_type{{':'}} core1"
   - name: Changing hostname on Core1
     lineinfile: dest=/etc/sysconfig/network line="HOSTNAME={{core1_hostname}}"
   - name: changing hostname on core1
     hostname: name={{core1_hostname}}
   - name: restart service on core1
     command: "service network restart"
- hosts: data0
  remote_user: root
  vars_files:
    - playbook_variables.yml
  tasks:
    - name: Adding a role to Data0
      lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="node_type{{':'}} data0"
    - name:   Changing hostname on Data0
      lineinfile: dest=/etc/sysconfig/network line="HOSTNAME={{data0_hostname}}"
    - name: changing hostname data0
      hostname: name={{data0_hostname}}
    - name: Restarting service on Data0
      command: "service network restart"
- hosts: data1
  remote_user: root
  vars_files:
    - playbook_variables.yml
  tasks:
    - name: Adding a role into Data1
      lineinfile: dest=/opt/illumio_pce_config/runtime_env.yml line="node_type{{':'}} data1"
    - name: Changing Hostname on Data1
      lineinfile: dest=/etc/sysconfig/network line="HOSTNAME={{data1_hostname}}"
    - name: changing hostname
      hostname: name={{data1_hostname}}
    - name: Restart service on Data1
      command: "service network restart"
- hosts: non_data
  remote_user: root
  vars_files:
    - playbook_variables.yml
  tasks:
    - name: Starting service on core0, core1, data0
      become: yes
      become_user: illumio
      environment:
        ILLUMIO_RUNTIME_ENV: /opt/illumio_pce_config/runtime_env.yml
      command: chdir=/opt/illumio_pce ./illumio-pce-ctl restart
    - pause: seconds=30

- hosts: data1
  remote_user: root
  vars_files:
    - playbook_variables.yml
  tasks:
    - name: Starting service on data1
      become: yes
      become_user: illumio
      environment:
        ILLUMIO_RUNTIME_ENV: /opt/illumio_pce_config/runtime_env.yml
      command: chdir=/opt/illumio_pce ./illumio-pce-ctl restart
    - pause: seconds=30

- hosts: data0
  remote_user: root
  vars_files:
    - playbook_variables.yml
  tasks:
    - name: Starting database on data0
      become: yes
      become_user: illumio
      environment:
        ILLUMIO_RUNTIME_ENV: /opt/illumio_pce_config/runtime_env.yml
      command: chdir=/opt/illumio_pce ./illumio-pce-db-management setup
- hosts: core0
  remote_user: root
  vars_files:
    - playbook_variables.yml
  tasks:
    - name: Starting run_level 5
      become: yes
      become_user: illumio
      environment:
        ILLUMIO_RUNTIME_ENV: /opt/illumio_pce_config/runtime_env.yml
      command: chdir=/opt/illumio_pce ./illumio-pce-ctl set-runlevel 5       

